config/routes.rb
Poker::Application.routes.draw do
  match "profile", to: 'profiles#show'

  match "statistic", to: 'profiles#statistic'

  resources :games do
    member do
       put :join
       put :exit
       put :start
       put :turn
       put :check
       put :raise_bet
       put :fold
       put :call
    end
  end

  devise_for :users

  root :to => 'games#index'

end

app/models/game.rb
class Game < ActiveRecord::Base
  has_one :deck
  GAME_BETS = (1..100)

  attr_accessible :name, :pot, :blind, :waiting, :bot_type
  belongs_to :user

  # validates :name, presence: true
  
  def set_status
    if self.started? && !self.flop? && !self.turn? && !self.river? && !self.ended?
      self.status = "flop"
      self.flop = true
    elsif self.flop? && self.started?
      self.status = "turn"
      self.flop = false
      self.turn = true
    elsif self.turn? && self.started?
      self.status = "river"
      self.turn = false
      self.river = true
    elsif self.river? && self.started?
      self.status = "ended"
      self.river = false
      self.ended = true
      self.started = false
    end
  end


  def take_bets(user)
    self.pot += self.blind*3
    user.credits -= self.blind
    user.save
  end

  def end_game
    self.pot = 0
    self.save
  end

  def aggressive? 
    self.bot_type == 'aggressive' ? true : false
  end

  def carefull? 
    self.bot_type == 'carefull' ? true : false
  end


end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_filter :authenticate_user!
  before_filter :check_owner, :except => [:index, :new, :create]
  before_filter :game_started?, :only => [:check, :raise_bet, :fold, :call]
  before_filter :initialize_session, :only => [:show]


  def initialize_session
    if !@game.started? && !@game.ended? 
      set_session_values
    end 
  end

  def repeated_start
    redirect_to @game, notice: "Game is already started" if @game.started?
  end

  def game_started?
    redirect_to @game, notice: "Click 'Start game' first." unless @game.started?
  end

  def check_owner
    @game = Game.find(params[:id])
    redirect_to games_path, notice: "This is not your game!" unless current_user.games.to_a.include? @game
  end
  include GamesHelper

  def start
    @game = Game.find(params[:id])
    @game.started = true
    @game.ended = false
    @game.status = "started"
    @game.take_bets(current_user)
    #@game.player_turn = [true, false].sample
    @game.player_turn = true
    session[:bot] = Bot.new
    @game.save
    set_session_values
    session[:deck].deal
    session[:player_cards].push session[:deck].deal
    session[:bot].cards.push session[:deck].deal
    session[:player_cards].push session[:deck].deal
    session[:bot].cards.push session[:deck].deal
    flash[:notice] = 'You started game.'
    redirect_to @game
  end

  def index
    @games = current_user.games
  end

  def show
    
    @game = Game.find(params[:id])
    if session[:bot].turn == "raise"
      flash[:notice] = "Bot bet #{session[:bot].bet}"
    end
    @player_hand = PokerHand.new(session[:player_cards] + session[:flop] +  session[:turn] + session[:river])
    @bot_hand = PokerHand.new(session[:bot].cards + session[:flop] +  session[:turn] + session[:river])
    if @game.ended?
      @game.started = false
      flash.now[:notice] = who_wins?(@player_hand, @bot_hand, session[:player_turn], session[:bot].turn)
      @player_hand = @bot_hand = PokerHand.new
      if flash[:notice] == "Player wins!"
        current_user.credits += @game.pot
        current_user.wins += 1
        if @game.aggressive?
          @game.aggressive_losts += 1
        else
          @game.carefull_losts += 1
        end 
      elsif flash[:notice] == "Bot wins!"
        if @game.aggressive?
          @game.aggressive_bank += @game.pot
          @game.aggressive_wins += 1
        else
          @game.carefull_bank += @game.pot
          @game.carefull_wins += 1
        end  
        current_user.losts += 1
      elsif flash[:notice] == "Friendship wins!"
        current_user.credits += @game.pot/2 
        if @game.aggressive?
          @game.aggressive_bank += @game.pot/2
        else
          @game.carefull_bank += @game.pot/2
        end  
      end
      session = []     
      current_user.save  
      warn current_user.credits.inspect
      @game.ended = false
      @game.pot = 0
      @game.save      
    end
  end

  def destroy
    @game = Game.find(params[:id])
    @game.destroy
    flash[:notice] = "Game is successfully deleted!"
    redirect_to root_path
  end 

  def new
    @game = Game.new
  end

  def create
    @game = current_user.games.new(params[:game])
    if @game.save
      redirect_to @game
      flash[:success] = "Game is successfully created!"
    else
      render :new
    end
  end

  def check
    @game = Game.find(params[:id])
    if !@game.ended?
      check_turn(@game)
      session[:bot].make_turn(@game, session[:player_turn], 0, session[:flop])
      @game.set_status
      @game.save
      give_cardz(@game)
      flash[:notice] = @game.status  
    else
      flash[:notice] = "Game is ended. Start new game."
    end
    redirect_to @game
  end

  def raise_bet
    @game = Game.find(params[:id])
    if !@game.ended?
      session[:player_turn] = "raise"
      bet = raise_turn(@game)
      session[:floop] = [] if session[:floop].nil?
      session[:bot].make_turn(@game, session[:player_turn], bet, session[:floop] + session[:river] + session[:turn])
      if session[:bot].turn == "fold"
        bot_fold_turn(@game)       
      end
    else
      flash[:notice] = "Game is ended. Start new game."
    end
    @game.set_status
    give_cardz(@game)
    flash[:notice] = @game.status
    @game.save
    redirect_to @game
  end

  def fold
    @game = Game.find(params[:id])
    if !@game.ended?
      player_fold_turn(@game)
      @game.save
    else
      flash[:notice] = "Game is ended. Start new game."
    end
    redirect_to @game
  end

  def call
    @game = Game.find(params[:id])
    if !@game.ended?
      call_turn(@game)
      @game.save
    else
      flash[:notice] = "Game is ended. Start new game."
    end
    flash[:notice] = @game.status
    redirect_to @game
  end

  def last
    current_user.games.order(:created_at)
  end

  private

  def give_cardz(game)
    if game.flop?
      session[:deck].deal
      3.times { session[:flop].push session[:deck].deal }
    elsif game.turn?
      session[:deck].deal
      session[:turn].push session[:deck].deal
    elsif game.river?
      session[:deck].deal
      session[:river].push session[:deck].deal
    end
  end

  def bot_turn(game, bet = nil)
    # session[:bot].make_turn(game, bet, session[:player_turn])
    if check?(session[:player_turn])
      session[:bot_turn] = "check"
    elsif raise?(session[:player_turn])
      session[:bot_turn] = "call"
      game.pot += bet.to_i
    end
    game.bot_turn = false
    game.player_turn = true
  end

  def raise_turn(game)
    game.bot_turn = true
    session[:player_turn] = "raise"
    game.pot += params[:raise_bet].to_i
    params[:raise_bet]
  end

  def check_turn(game)
      game.player_turn = !game.player_turn
      game.bot_turn = true
      session[:player_turn] = "check"
  end

  def player_fold_turn(game)
      session[:player_turn] = "fold"
      game.status = "Player fold"
      common_fold_things(game)
  end

  def bot_fold_turn(game)
    game.status = "Bot fold"
    common_fold_things(game)
  end

  def check_game_status
    @game = Game.find(params[:id])
    if @game.pending?
      flash[:notice] = "You should start game first."
    end
    redirect_to :back
  end

  def call_turn(game)
    game.set_status
    give_cardz(game)
    current_user.credits -= session[:bot].bet
    current_user.save
    game.pot += session[:bot].bet
    session[:player_turn] = "call"
    session[:bot].turn = "raise called"
  end


  def common_fold_things(game)
      game.ended = true
      game.started = false
      game.flop = false
      game.river = false
      game.turn = false
  end 


end

app/helpers/games_helper.rb
module GamesHelper
  include ApplicationHelper

  def who_wins?(player_hand, bot_hand, player_turn, bot_turn) 
    if (player_hand > bot_hand)
      message = "Player wins!"
    elsif (player_hand < bot_hand)
      message ="Bot wins!" 
    elsif player_hand == bot_hand
      message = "Friendship wins!"
    end
    if fold? player_turn
      message ="Bot wins!"     
    end  
    if fold? bot_turn
      message ="Player wins!" 
    end
    message
  end

  def set_session_values
    session[:deck] = Deck.new
    session[:player_cards] = []
    session[:flop] = []
    session[:turn] = []
    session[:river] = []
    session[:player_turn] = ""
    session[:bot] = Bot.new
  end
end

app/views/games/_form.html.erb
<%= form_for @game do |f| %>

<%if @game.errors.any?%>
	<div id="error_explanation">
	  <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>
	    <ul>
	      <% @game.errors.full_messages.each do |msg| %>
	        <li><%= msg %></li>
	      <% end %>
	    </ul>
	</div>
<% end %>

 <div class="field">
	 <%= f.label :blind%>
   <%= f.select :blind, (1..10) %>
 </div>

  <div class="field">
	 <%= f.label :bot_type %>
   <%= f.select :bot_type, ['aggressive', 'carefull'] %>
 </div>

  <div class="actions">
    <%= f.submit "Create game",:class => 'btn btn-primary' %>
  </div>

 <% end %>

app/views/games/delete.html.erb
<h1>Game#delete</h1>
<p>Find me in app/views/game/delete.html.erb</p>

app/views/games/edit.html.erb
<h1>Game#edit</h1>
<%= render 'form' %>

app/views/games/index.html.erb
<h1>Your games</h1>
<% if !@games.empty? %>
<% @games.each do |game| %>
	<p>
	<%= link_to "game_#{game.id}", game %>
	<%= link_to "Destroy", game, method: :delete, confirm: "Are you sure ?", class: "p-l-50" %>
	</p>
<% end %>
<% else %>
    No games created yet.
<% end %>

app/views/games/new.html.erb
<h1>New Game</h1>
<%= render 'form' %>

app/views/games/show.html.erb
<h2>Game pot: <%= @game.pot %></h2>
<h2>Game blind: <%= @game.blind %></h2>
<h2>Game status: <%= @game.status %></h2>
  <div class="card_div">
    <% if !session[:flop].empty? %>
      <% session[:flop].each do |card|%> 
        <%= image_tag("/assets/#{card.to_s.last}/#{card.to_s.first}.png", class: 'card')%>
      <% end %>
    <% end %>
    <% if !session[:turn].empty? %>
      <% session[:turn].each do |card|%> 
        <%= image_tag("/assets/#{card.to_s.last}/#{card.to_s.first}.png", class: 'card')%>
      <% end %>
    <% end %>
    <% if !session[:river].empty? %>
      <% session[:river].each do |card|%> 
        <%= image_tag("/assets/#{card.to_s.last}/#{card.to_s.first}.png", class: 'card')%>
      <% end %>
    <% end %>
  </div>
<%# if @game.started? %>
<%#= link_to "Exit game", exit_game_path, :method => :put %>
<% unless session[:player_cards].empty? %>
    <p class="player">
      My cards
    </p>
  <% session[:player_cards].each do |card| %>

    <%= image_tag("/assets/#{card.to_s.last}/#{card.to_s.first}.png", class: 'card')%>
  <% end %>
<% end %>
    
<% if @game.started?  %>

  <% if raise?(session[:bot].turn) %>
    <%= form_tag call_game_path, :method => :put do%>
      <%= submit_tag "Call", :class => 'btn btn-warning' %>
    <% end %>

    <%= form_tag raise_bet_game_path, :method => :put do%>
      <%= select_tag :raise_bet, options_for_select((1..100)) %>
      <%= submit_tag "Raise", :class => 'btn btn-primary' %>
    <% end %>

    <%= form_tag fold_game_path, :method => :put do%>
      <%= submit_tag "Fold", :class => 'btn btn-danger' %>
    <% end %>
  
  <% else %>

    <%= form_tag check_game_path, :method => :put do%>
      <%= submit_tag "Check",:class => 'btn btn-success' %>
    <% end %>

    <%= form_tag raise_bet_game_path, :method => :put do%>
      <%= select_tag :raise_bet, options_for_select((1..100)) %>
      <%= submit_tag "Raise", :class => 'btn btn-primary' %>
    <% end %>

    <%= form_tag fold_game_path, :method => :put do%>
      <%= submit_tag "Fold", :class => 'btn btn-danger' %>
    <% end %>

  <% end %>

<% end %>
<% unless @game.started? %>
<p><%= link_to "Start game", start_game_path, :method => :put, :class => 'btn btn-primary'%></p>
<% end %>

app/views/games/update.html.erb
<h1>Game#update</h1>
<p>Find me in app/views/game/update.html.erb</p>