config/routes.rb
Poker::Application.routes.draw do
  match "profile", to: 'profiles#show'

  match "statistic", to: 'profiles#statistic'

  resources :games do
    member do
       put :join
       put :exit
       put :start
       put :turn
       put :check
       put :raise_bet
       put :fold
       put :call
    end
  end

  devise_for :users

  root :to => 'games#index'

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Poker Trainer</a>
    by Team#4
  </small>
  <nav>
    <ul>
      <li><%#= link_to "About",   about_path %></li>
      <li><%#= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="row-fluid">
  
      <%= link_to "poker trainer", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%#= link_to "Help", help_path %></li>
          <% if signed_in? %>
              <li class="white">Hello, <%= current_user.email %>! You have <%= current_user.credits %> credits.</li>
              <li id="fat-menu" class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  Account <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Profile", profile_path %></li>
                  <li><%= link_to "Settings", edit_user_registration_path(current_user) %></li>
                  <li><%= link_to "Sign out", destroy_user_session_path, method: "delete" %></li>
                  <li class="divider"></li>
                  <li><%= link_to "Create game", new_game_path%></li>
                  <li><%= link_to "My games", games_path%></li>
                  <li><%= link_to "Bot statistic", statistic_path%></li>
                </ul>
              </li>
          <% else %>
              <li><%= link_to "Sign in", new_user_session_path %></li>
          <% end %>
        </ul>
      </nav>
   
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
<%= render 'layouts/header' %>
  <div class="row-fluid">
    <div class="container">
      <% flash.each do |key, value| %>
          <%= content_tag(:div, value, class: "alert alert-#{key}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </div>
</body>
</html>